steps:
  - name: 'java:8'
    env: ['GRADLE_USER_HOME=cache']
    entrypoint: 'bash'
    args: ['-c', './gradlew build']
  - name: 'gcr.io/cloud-builders/gradle'
    args: [':micronaut-guide:jibDockerBuild']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'micronaut-guide:$TAG_NAME', 'gcr.io/$PROJECT_ID/micronaut-guide:$TAG_NAME']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/micronaut-guide:$TAG_NAME']
