steps:
  - name: 'java:8'
    env: ['GRADLE_USER_HOME=cache']
    entrypoint: 'bash'
    args: ['-c', './gradlew build']
  - name: 'gcr.io/cloud-builders/gradle'
    args: [':micronaut-guide:jibDockerBuild']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', '${_IMAGE_NAME}:$TAG_NAME', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['run', '${_DEPLOYMENT_NAME}', '--image=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$TAG_NAME', '--port=8080']
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['expose', 'deployment', '${_DEPLOYMENT_NAME}', '--type=LoadBalancer']
