micronaut:
    application:
        name: examples
    server:
        port: 8080
        cors:
            enabled: true
endpoints:
    info:
        enabled: true
        sensitive: false
    health:
        enabled: true